### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by hathawayj** [HBGDki/datasus#1]
@hafen can you give me write access?

**Comment by hafen** [comment]
Yes I'll do that right now. You'll want to do a pull (and re-pull down data from OSF as well) and merge things with yours before pushing though since I've changed some things (variable names, etc.).

**Comment by hafen** [comment]
Actually can you just fork and pull request? I think that will be easier than us stomping each other's code on without the other knowing.

**Comment by hathawayj** [comment]
Ok.
